import { ClerkProvider } from "@clerk/nextjs";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { type AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import Header from "~/components/Header";
import ProductsProvider from "~/providers/ProductsProvider";
import StoreProvider from "~/providers/StoreProvider";
import StoreStatusProvider from "~/providers/StoreStatusProvider";
import { UserProvider } from "~/providers/UserProvider";
import axios from 'axios';

import "~/styles/globals.css";
import { useEffect } from "react";

const MyApp: AppType = ({ Component, pageProps }) => {
  const queryClient = new QueryClient();
//  useEffect(()=>{reqFun()},[])
//  const reqFun = async () => {
//   try {
//     let data = JSON.stringify({
//       "user": {
//         "uid": "123",
//         "displayName": "John Doe",
//         "email": "john@example.com",
//         "phoneNumber": "+123456789",
//         "photoURL": "https://example.com/profile.jpg",
//         "metadata": {
//           "creationTime": "2022-03-10T12:00:00Z",
//           "lastSignInTime": "2022-03-10T12:00:00Z"
//         }
//       }
//     });
    
//     let config = {
//       method: 'post',
//       maxBodyLength: Infinity,
//       url: 'http://localhost:3000/api/add-user',
//       headers: { 
//         'Content-Type': 'application/json'
//       },
//       data : data
//     };
    
//     axios.request(config)
//     .then((response) => {
//       console.log(JSON.stringify(response.data));
//     })
//     .catch((error) => {
//       console.log(error);
//     });
    
//   } catch (error) {
    
//   }
//  }
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
        <QueryClientProvider client={queryClient}>
          <StoreProvider>
              <ProductsProvider>
                <>
                  <Head>
                    <title>Pineapple store</title>
                    <meta
                      name="description"
                      content="Generated by create-t3-app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                  </Head>
                  <Header />
                </>
                <Component {...pageProps} />
              </ProductsProvider>
          </StoreProvider>
        </QueryClientProvider>
    </ClerkProvider>
  );
};

export default MyApp;
